# Generated by Django 6.0.6 on 2026-06-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('org_type', models.CharField(choices=[('university', "Oliy ta'lim muassasasi"), ('hospital', 'Kasalxona')], max_length=20, verbose_name='Turi')),
                ('code', models.CharField(help_text='Qisqa identifikator (masalan: TDTU, TOSHMI)', max_length=50, unique=True, verbose_name='Kod')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Muassasa',
                'verbose_name_plural': 'Muassasalar',
                'ordering': ['name'],
            },
        ),
    ]
