# Generated by Django 6.0.6 on 2026-06-04 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('bone_age', "Suyak yoshi (Qo'l rentgeni)"), ('prostate', 'Prostata saraton'), ('pneumonia', "O'pka yallig'lanishi")], max_length=20)),
                ('image', models.ImageField(upload_to='xrays/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Tahlil qilinmoqda'), ('completed', 'Tugallandi'), ('error', 'Xato')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tahlil',
                'verbose_name_plural': 'Tahlillar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255)),
                ('diagnosis_type', models.CharField(choices=[('normal', 'Normal'), ('warning', "E'tibor talab"), ('danger', 'Patologiya')], max_length=10)),
                ('confidence', models.FloatField()),
                ('note', models.TextField(blank=True)),
                ('gradcam_image', models.ImageField(blank=True, null=True, upload_to='gradcam/%Y/%m/')),
                ('raw_output', models.JSONField(default=dict)),
                ('doctor_confirmed', models.BooleanField(blank=True, null=True)),
                ('doctor_note', models.TextField(blank=True)),
                ('doctor_report', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysis')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tahlil natijasi',
                'verbose_name_plural': 'Tahlil natijalari',
            },
        ),
    ]
