# Generated by Django 6.0.6 on 2026-06-04 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Tizimga kirish'), ('logout', 'Tizimdan chiqish'), ('register', "Ro'yxatdan o'tish"), ('upload', 'Rasm yuklash'), ('analyze', 'Tahlil boshlash'), ('result_view', "Natijani ko'rish"), ('doctor_confirm', 'Shifokor tasdiqladi'), ('doctor_report', 'AI xatosi hisoboti'), ('payment', "To'lov")], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='analysis.analysis')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit loglar',
                'ordering': ['-timestamp'],
            },
        ),
    ]
