# Generated by Django 6.0.6 on 2026-06-04 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_diagnosis', models.CharField(blank=True, max_length=255)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('ai_raw_output', models.JSONField(default=dict)),
                ('error_type', models.CharField(blank=True, choices=[('low_confidence', 'Past ishonch'), ('service_error', 'Servis xatosi'), ('timeout', 'Vaqt tugadi')], max_length=30, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('doctor_verdict', models.BooleanField(blank=True, null=True)),
                ('doctor_note', models.TextField(blank=True)),
                ('flagged_for_training', models.BooleanField(default=False)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_log', to='analysis.analysis')),
            ],
            options={
                'verbose_name': 'Tahlil logi',
                'verbose_name_plural': 'Tahlil loglari',
                'ordering': ['-created_at'],
            },
        ),
    ]
